config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :update, :destroy]

  # GET /places
  def index
    @places = Place.all

    render json: @places
  end

  # GET /places/1
  def show
    render json: @place
  end

  # POST /places
  def create
    @place = Place.new(place_params)

    if @place.save
      render json: @place, status: :created, location: @place
    else
      render json: @place.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /places/1
  def update
    if @place.update(place_params)
      render json: @place
    else
      render json: @place.errors, status: :unprocessable_entity
    end
  end

  # DELETE /places/1
  def destroy
    @place.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def place_params
      params.require(:place).permit(:lat, :lng, :address, :available, :user_id)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]

  # GET /users
  def index
    @users = User.all

    render json: @users
  end

  # GET /users/1
  def show
    render json: @user
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      render json: @user, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :phone)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Homein</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        
        <script defer src="https://maps.googleapis.com/maps/api/js" ></script>
        
        <!-- Fontawesome -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    </head>
    
    <body>
        <p id="notice"><%= notice %></p>
        <p id="alert"><%= alert %></p>
        
        <div class="container <%= params[:action] %>" id="main">
            <%= yield %>
                
                <% if user_signed_in? %>
                    <ul id="navigation_links">
                		<%= link_to root_path, :title => "Home" do %>
                		    <i class="fa fa-home"></i>
                		<% end %>
                    	<%= link_to current_user_places_path, :id => "logged_in", :title => "View your places" do %>
                            <i class="fa fa-user"></i>
                    	<% end %>
                	    <%= link_to destroy_user_session_path, :method => :delete, :id => "logout", :title => "Logout" do %>
                            <i class="fa fa-sign-out"></i>
                	    <% end %>
                	    <%= link_to new_place_path, :title => "Add a place" do %>
                	      <i class="fa fa-plus"></i>
                	    <% end %>
                	</ul>
                <% else %>
                    <ul id="navigation_links">
                        <%= link_to root_path do %>
                	        <i class="fa fa-home"></i>
                	    <% end %>
                		<%= link_to new_user_session_path, :id => "login", :title => "Login" do %>
                		    <i class="fa fa-sign-in"></i>
                		<% end %>
                	    <%= link_to new_user_registration_path, :id => "register", :title => "Register" do %> 
                            <i class="fa fa-user-plus"></i>
                	    <% end %>
                	</ul>
                <% end %>
            </div> <!-- Close the options container -->
        </div>
    </body>
</html>

app/views/places/_facets.html.erb
<div id="facets" class="container">
    <%= form_tag places_url, :method => 'get', :id => "places_filter" do %>
        <div id="sliders" class="container">
            <div class="container">
                <%= label_tag :price %>
                
                <%= number_field_tag "price[min]", params.has_key?('price') ? params['price']['min'] : nil, :id => "min_price", :min => Place.minimum(:price), :max => Place.maximum(:price), :style => "width:#{Place.maximum(:price).to_s.length}em;" %>
                
                <div class="slider" id="price" data-min="<%= Place.minimum(:price) %>" data-max="<%= Place.maximum(:price) %>" data-low="<%= params.has_key?('price') && !params[:price][:min].blank? ? params['price']['min'] : Place.minimum(:price) %>" data-high="<%= params.has_key?('price') && !params[:price][:max].blank? ? params['price']['max'] : Place.maximum(:price) %>"></div>
                
                <%= number_field_tag "price[max]", params.has_key?('price') ? params['price']['max'] : nil, :id => "max_price", :min => Place.minimum(:price), :max => Place.maximum(:price), :style => "width:#{Place.maximum(:price).to_s.length}em;" %>
            </div>
            
            <div class="container">
                <%= label_tag :rooms %>
                
                <%= number_field_tag "rooms[min]", params.has_key?('rooms') ? params['rooms']['min'] : nil, :id => "min_rooms", :min => Place.minimum(:rooms), :max => Place.maximum(:rooms), :style => "width:#{Place.maximum(:rooms).to_s.length}em;" %>
                
                <div class="slider" id="rooms" data-min="<%= Place.minimum(:rooms) %>" data-max="<%= Place.maximum(:rooms) %>" data-low="<%= params.has_key?('rooms') && !params[:rooms][:min].blank? ? params['rooms']['min'] : Place.minimum(:rooms) %>" data-high="<%= params.has_key?('rooms') && !params[:rooms][:max].blank? ? params['rooms']['max'] : Place.maximum(:rooms) %>"></div>
                
                <%= number_field_tag "rooms[max]", params.has_key?('rooms') ? params['rooms']['max'] : nil, :id => "max_rooms", :min => Place.minimum(:rooms), :max => Place.maximum(:rooms), :style => "width:#{Place.maximum(:rooms).to_s.length}em;" %>
            </div>
            
            <div class="container">
                <%= label_tag :bathrooms %>
                
                <%= number_field_tag "bathrooms[min]", params.has_key?('bathrooms') ? params['bathrooms']['min'] : nil, :id => "min_bathrooms", :min => Place.minimum(:bathrooms), :max => Place.maximum(:bathrooms), :style => "width:#{Place.maximum(:bathrooms).to_s.length}em;" %>
                
                <div class="slider" id="bathrooms" data-min="<%= Place.minimum(:bathrooms) %>" data-max="<%= Place.maximum(:bathrooms) %>" data-low="<%= params.has_key?('bathrooms') && !params[:bathrooms][:min].blank? ? params['bathrooms']['min'] : Place.minimum(:bathrooms) %>" data-high="<%= params.has_key?('bathrooms') && !params[:bathrooms][:max].blank? ? params['bathrooms']['max'] : Place.maximum(:bathrooms) %>"></div>
                
                <%= number_field_tag "bathrooms[max]", params.has_key?('bathrooms') ? params['bathrooms']['max'] : nil, :id => "max_bathrooms", :min => Place.minimum(:bathrooms), :max => Place.maximum(:bathrooms), :style => "width:#{Place.maximum(:bathrooms).to_s.length}em;" %>
            </div>
        </div>
        
        <div class="container">
            <div id="for_container" class="container">
                <%= label_tag :for, "For: " %>
            
                <%= select_tag "for", options_for_select(["Sale", "Rent"], params.has_key?('for') ? params['for'] : "" ), include_blank: "Both" %>
            </div>
            
            <%= text_field_tag :query, params[:query], :placeholder => "Search..." %>
        </div>
        
        <%= submit_tag "Submit" %>
    <% end %>
</div>

app/views/places/_form.html.erb
<%= form_for(@place, :html => { multipart: true }) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <textarea name="place[description]" id="place_description">
        <%= @place.description %>
    </textarea>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field" id="latitude_field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field" id="longitude_field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :rooms %><br>
    <%= f.number_field :rooms %>
  </div>
  <div class="field">
    <%= f.label :bathrooms %><br>
    <%= f.number_field :bathrooms %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field" id="for_field">
      <%= f.label :for %><br>
      <%= f.select :for, [["Rent", "Rent"], ["Sale", "Sale"]] %>
  </div>
  <%= f.fields_for(:pictures, Picture.new) do |ff| %>
      <div class="field">
          <%= ff.label :image %>
          <%= ff.file_field :image, :multiple => true, :name => "place[pictures_attributes][][image]" %>
      </div>
  <% end %>
  <% @pictures.each do |picture| %>
    <%= link_to place_picture_path(@place, picture), method: :delete, data: {confirm: "Are you sure? This will delete this picture."}, :title => "Delete this picture" do %>
      <%= image_tag picture.image.url(:small) %>
    <% end %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/_map.html.erb
<div id="map" class="container">
    <div id="map-canvas" data-latitude="<%= place.latitude %>" data-longitude="<%= place.longitude %>" data-marker-draggable="<%= defined?(draggable_marker) ? draggable_marker : '' %>"></div>
</div>

app/views/places/_pictures.html.erb
<p>Pictures: </p>

<div id="pictures">
    <% place.pictures.each do |picture| %>
        <%= link_to(picture.image.url, target: "_blank") do %>
            <%= image_tag(picture.image) %>
        <% end %>
    <% end %>
</div>

app/views/places/_place.html.erb
<h1 class="address">
    <% if params[:action] == "show" %>
        <%= place.address %>
    <% else %>
        <%= link_to(place.address, place) %>
    <% end %>
</h1>

<p class="description"><%= place.description %></p>

<p>
    Price: <span class="price"><%= place.price.to_s(:currency) %></span>, For: <spa class="for"><%= place.for.capitalize %></span>
</p>

<p>
    Rooms: <span class="rooms"><%= place.rooms %></span>, Bathrooms: <span class="bathrooms"><%= place.bathrooms %></span>
</p>

<p><%= mail_to(place.user.email) %></p>

<% if defined?(map) && map == true %>
    <%= render 'map', place: place %>
<% end %>

<% if place.pictures.count > 0 %>
    <%= render 'pictures', place: place %>
<% end %>

<% if place.user == current_user %>
    <%= link_to 'Edit', edit_place_path(place) %>
    
    <%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/places/edit.html.erb
<div id="content" class="container">
    <%= render 'form' %>
    
    <%= render 'map', place: @place, draggable_marker: true %>
</div>

<div id="options" class="container">

app/views/places/index.html.erb
<div id="content" class="container">
    <div id="listings" class="container">
        <%= div_for(@places, :class => "listing container") do |place| %>
            <%= render place %>
        <% end %>
    </div>
    
    <div id="infiniteScrolling">
        <%= will_paginate @places %>
    </div>
</div>

<div id="options" class="container">
    <%= render 'facets' %>

app/views/places/index.js.erb
var content = '<%= j div_for(@places, :class => "listing container") { |place| render place } %>'

console.log(content);

$('#listings.container').append(content);

<% if @places.next_page %>
    $('#infiniteScrolling').html('<%= j will_paginate @places %>');
<% else %>
    $(window).off('scroll');
    
    $('.pagination').remove();
<% end %>

app/views/places/new.html.erb
<div id="content" class="container">
    <%= render 'form' %>
    
    <%= render 'map', place: @place, draggable_marker: true %>
</div>

<div id="options" class="container">

app/views/places/show.html.erb
<div id="content" class="container">
    <div id="listing" class="container">
        <%= render @place, map: true %>
    </div>
</div>
    
<div id="options" class="container">

app/views/places/your_places.html.erb
<div id="content" class="container">
    <%= render @places %>
</div>

<div id="options" class="container">